services:
  app:
    container_name: bxyz
    build: .
    ports:
      - "4321:4321"
      - "3000:3000"
    environment:
      - PUBLIC_PB_URL=https://api.breadone.net
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: bxyz-pb
    restart: always
    # command:
      # - --encryptionEnv
      # - ENCRYPTION 
      # - serve
      # - 0.0.0.0:8080
    ports:
      - "8091:8090"
      - "8081:8080"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_public:/pb_public 
      - ./pb_migrations:/pb_migrations 
    healthcheck: 
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5