name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: breadone1/bxyz

  update-server:
    runs-on: ubuntu-latest

    steps:
    - name: deploy to server
      uses: appleboy/ssh-action@v1.2.0
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY }}
          script: bash /home/ubuntu/servers/breadone.xyz/redeploy.sh